export const userPublicSelect = {
  id: true,
  email: true,
  firstName: true,
  lastName: true,
  displayName: true,
  username: true,
  phone: true,
  status: true,
  isOnline: true,
  emailVerified: true,
  role: true,
  lastLogin: true,
  lastSeenAt: true,
  createdAt: true,
  updatedAt: true,
  profileImage: true,
  store: { select: { id: true, name: true } },
} as const;
