export const storePublicSelect = {
  id: true,
  name: true,
  tagline: true,
  description: true,
  email: true,
  phone: true,
  address: true,
  website: true,
  logo: true,
  banner: true,
  facebook: true,
  instagram: true,
  twitter: true,
  youtube: true,
  status: true,
  isFeatured: true,
  featuredUntil: true,
  keywords: true,
  metaTitle: true,
  metaDesc: true,
  businessHours: true,
  ownerId: true,
  createdAt: true,
  updatedAt: true,
} as const;

export const ownerPublicSelect = {
  id: true,
  email: true,
  username: true,
  phone: true,
  status: true,
  isOnline: true,
  emailVerified: true,
  role: true,
  firstName: true,
  lastName: true,
  displayName: true,
  profileImage: true,
  lastLogin: true,
  lastSeenAt: true,
  createdAt: true,
  updatedAt: true,
} as const;

